baseURL: "https://ahmadiehsan.github.io/"
theme: "hyde-hyde"
publishDir: "docs"

DefaultContentLanguage: en
languages:
  fa:
    languageCode: "fa-ir"
    languageName: "فا"
    title: "احسان احمدی"
    languagedirection: rtl
    layoutReverse: true
    weight: 2
    menus:
      main:
      - name: "رزومه"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "تماس"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "احسان احمدی"
      title: "وبلاگ شخصی احسان احمدی"
      description: |
        Senior Python Developer and Software Architect
        ____________________
        همراه: 09198083006
        سربازی: کارت پایان خدمت
        (پروژه جایگزین خدمت)
        سن:27
        
  en:
    languageCode: "en-us"
    languageName: "en"
    title: "Ehsan Ahmadi"
    weight: 1
    menus:
      main:
      - name: "My Resume"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "Contact Me"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "Ehsan Ahmadi"
      title: "Ehsan Ahmadi Personal Blog"
      description: |
        Senior Python Developer and Software Architect
        ____________________
        1374ea@gmail.com
        (+98) 919 808 3006
        Age: 27

params:
  authorimage: "/img/ehsan_ahmadi.jpeg"
  mainSections: "posts"
  highlightjs: true
  highlightjsstyle: "github"
  postNavigation: false
  since: "2019"
  copyright: "| Ahmadi"
  social:
    github: "ahmadiehsan"
    linkedin: "ahmadi-ehsan"
    telegram: "ahmadi_ehsan"

