baseURL: "https://ahmadiehsan.github.io/"
theme: "hyde-hyde"
publishDir: "docs"

DefaultContentLanguage: fa
languages:
  fa:
    languageCode: "fa-ir"
    languageName: "فا"
    title: "احسان احمدی"
    languagedirection: rtl
    layoutReverse: true
    weight: 2
    menus:
      main:
      - name: "رزومه"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "تماس"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "احسان احمدی"
      title: "وبلاگ شخصی احسان احمدی"
      description: "سرپرست فنی سامانه درس‌آپ\n09198083006\nسن: 26"
  en:
    languageCode: "en-us"
    languageName: "en"
    title: "Ehsan Ahmadi"
    weight: 1
    menus:
      main:
      - name: "My Resume"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "Contact Me"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "Ehsan Ahmadi"
      title: "Ehsan Ahmadi Personal Blog"
      description: "Software Technical Lead\n1374ea@gmail.com\nAge: 26"

params:
  authorimage: "/img/ehsan_ahmadi.jpeg"
  mainSections: "posts"
  highlightjs: true
  highlightjsstyle: "github"
  postNavigation: false
  since: "2019"
  copyright: "| Ahmadi"
  social:
    github: "ahmadiehsan"
    linkedin: "ahmadi-ehsan"
    telegram: "ahmadi_ehsan"

